apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: uber-app-monitor
  namespace: test
  labels:
    release: my-prometheus
spec:
  selector:
    matchLabels:
      app: uber-app
  namespaceSelector:
    matchNames:
      - test
  endpoints:
    - port: http-metrics
      path: /actuator/prometheus
      interval: 30s