apiVersion: apps/v1
kind: Deployment
metadata:
  name: map-deployment
  namespace: test
  labels:
    app: map-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: map-app
  template:
    metadata:
      labels:
        app: map-app
    spec:
      containers:
        - name: map-container
          image: map:1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 8081