apiVersion: apps/v1
kind: Deployment
metadata:
  name: map-deployment
  namespace: test
  labels:
    app: map-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: map-app
  template:
    metadata:
      labels:
        app: map-app
      annotations:
        # These annotations tell Prometheus to scrape this pod
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "8081"
    spec:
      containers:
        - name: map-container
          image: map:2.0
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: map-service
  namespace: test
  labels:
    app: map-app # Make sure this label is here
spec:
  type: ClusterIP
  selector:
    app: map-app
  ports:
    - name: http-metrics  # Add this name
      protocol: TCP
      port: 80
      targetPort: 8081