apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: map-service-destrule # Use one consistent name
  namespace: test
spec:
  host: map-service.test.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN # (Optional) Global policy for this host
  subsets:
    - name: v1
      labels:
        version: v1
    - name: v2
      labels:
        version: v2