apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: istio-proxies-monitor
  namespace: monitoring
  labels:
    release: kube-prometheus-stack # IMPORTANT: This must match your Prometheus selector
spec:
  selector:
    matchExpressions:
      - {key: istio-prometheus-ignore, operator: DoesNotExist}
  podMetricsEndpoints:
    - port: http-envoy-prom   # This is the name for port 15020
      path: /stats/prometheus
      interval: 15s
  namespaceSelector:
    any: true # This allows it to look into your "test" namespace