apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: map-app-monitor
  namespace: test
  labels:
    release: my-prometheus # Ensure this matches your Helm release name
spec:
  selector:
    matchLabels:
      app: map-app
  namespaceSelector:
    matchNames:
      - test
  endpoints:
    - port: http-map # This matches the port name in your Deployment/Service
      path: /actuator/prometheus
      interval: 30s